/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.allaybotai.view;

import com.mycompany.allaybotai.controller.GameController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Ismael
 */
public class CreditsView extends javax.swing.JFrame {

    /**
     * Creates new form Creditos
     */
    
    //Controller
    private final GameController controller;

    public CreditsView(GameController controller) {
        this.controller = controller;
        
        //Removes tittle bar and borders
        this.setUndecorated(true);

        //Start components and location
        initComponents();
        this.setLocationRelativeTo(null);

        //Create a final instance of itself and set the operation when closing to none
        final CreditsView view = this;
        view.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        //Window listener to return to Start Menu when closing the credits window
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                controller.goToStartMenu(view);
            }
        });
        setIconImage(new ImageIcon(getClass().getResource("/images/tesoro1_icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCreditos = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JLabel();
        txtAtentamente = new javax.swing.JLabel();
        btnStartMenu = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AllayQuest: Creditos");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCreditos.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtCreditos.setForeground(new java.awt.Color(0, 0, 0));
        txtCreditos.setText("Creditos");
        jPanel1.add(txtCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        txtNombre1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre1.setText("Ricardo Valencia");
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        txtNombre2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtNombre2.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre2.setText("Jose Villa");
        jPanel1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        txtNombre3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtNombre3.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre3.setText("Ismael Viloria");
        jPanel1.add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        txtAtentamente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtAtentamente.setForeground(new java.awt.Color(0, 0, 0));
        txtAtentamente.setText("Att: Con amor para la estimada.");
        jPanel1.add(txtAtentamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        btnStartMenu.setBackground(new java.awt.Color(204, 255, 255));
        btnStartMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnStartMenu.setText("Menu Principal");
        btnStartMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMenuMouseClicked(evt);
            }
        });
        jPanel1.add(btnStartMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descarga_resized.gif"))); // NOI18N
        jPanel1.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Return to StartMenu
    private void btnStartMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMenuMouseClicked
        controller.goToStartMenu(this);
    }//GEN-LAST:event_btnStartMenuMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Creditos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartMenu;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAtentamente;
    private javax.swing.JLabel txtCreditos;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtNombre2;
    private javax.swing.JLabel txtNombre3;
    // End of variables declaration//GEN-END:variables
}
