/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.allaybotai.view;

import com.mycompany.allaybotai.controller.GameController;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.awt.*;

/**
 *
 * @author Ismael
 */
public class StartMenuView extends javax.swing.JFrame {

    private final GameController controller;

    public StartMenuView(GameController controller) {
        this.controller = controller;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/tiles/front.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BttnSalir = new javax.swing.JButton();
        BttnCreditos = new javax.swing.JButton();
        BttnJugar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AllayQuest");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 246, 218));
        jLabel1.setText("Guardians Of The Ancient Forest");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 730, 90));

        BttnSalir.setBackground(new java.awt.Color(45, 115, 50));
        BttnSalir.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        BttnSalir.setForeground(new java.awt.Color(0, 0, 0));
        BttnSalir.setText("Exit");
        BttnSalir.setBorder(null);
        BttnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(BttnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 150, 40));

        BttnCreditos.setBackground(new java.awt.Color(116, 170, 107));
        BttnCreditos.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        BttnCreditos.setForeground(new java.awt.Color(0, 0, 0));
        BttnCreditos.setText("Credits");
        BttnCreditos.setBorder(null);
        BttnCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttnCreditosMouseClicked(evt);
            }
        });
        jPanel1.add(BttnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 150, 140));

        BttnJugar.setBackground(new java.awt.Color(208, 212, 118));
        BttnJugar.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        BttnJugar.setForeground(new java.awt.Color(0, 0, 0));
        BttnJugar.setText("Play");
        BttnJugar.setBorder(null);
        BttnJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttnJugarMouseClicked(evt);
            }
        });
        BttnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(BttnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/startScreen.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BttnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BttnSalirMouseClicked

    private void BttnJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttnJugarMouseClicked
        controller.goToMainGame(this);
    }//GEN-LAST:event_BttnJugarMouseClicked

    private void BttnCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttnCreditosMouseClicked
        controller.goToCredits(this);
    }//GEN-LAST:event_BttnCreditosMouseClicked

    private void BttnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnJugarActionPerformed
        controller.goToMainGame(this);

    }//GEN-LAST:event_BttnJugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnCreditos;
    private javax.swing.JButton BttnJugar;
    private javax.swing.JButton BttnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
